print("Hello World!")
print("Hello Again")
print("I like typing this")
print("This is very funny")
print('Yay! it is Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
#print("This an other random sentence")
